/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PaymentInterface extends ethers.utils.Interface {
  functions: {
    "index()": FunctionFragment;
    "priceInWei()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "index", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceInWei",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "index", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceInWei", data: BytesLike): Result;

  events: {};
}

export class Payment extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PaymentInterface;

  functions: {
    index(overrides?: CallOverrides): Promise<[BigNumber]>;

    "index()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    priceInWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    "priceInWei()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  index(overrides?: CallOverrides): Promise<BigNumber>;

  "index()"(overrides?: CallOverrides): Promise<BigNumber>;

  priceInWei(overrides?: CallOverrides): Promise<BigNumber>;

  "priceInWei()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    index(overrides?: CallOverrides): Promise<BigNumber>;

    "index()"(overrides?: CallOverrides): Promise<BigNumber>;

    priceInWei(overrides?: CallOverrides): Promise<BigNumber>;

    "priceInWei()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    index(overrides?: CallOverrides): Promise<BigNumber>;

    "index()"(overrides?: CallOverrides): Promise<BigNumber>;

    priceInWei(overrides?: CallOverrides): Promise<BigNumber>;

    "priceInWei()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    index(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "index()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceInWei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "priceInWei()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
